server:
  port: 8090
  
eureka:
  client:
     service-url:
        defaultZone: http://localhost:8762/eureka/
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/api/v1/orders/**
      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/api/v1/customer/**   

